# -*- coding: utf-8 -*-
##############################################################################
#
#    Odoo SA, Open Source Management Solution, third party addon
#    Copyright (C) 2022- Vertel AB (<https://vertel.se>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program. If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

import logging

from odoo import api, fields, models

_logger = logging.getLogger(__name__)


class CrmLead(models.Model):
    """Extends CRM leads with the fields captured by a badge scan.

    Design decision D1: the lead is a plain ``crm.lead`` rather than a new
    model, so the whole CRM flow - activities, pipeline, conversion, mass
    mailing - applies to scanned leads without any bridging.
    """
    _inherit = 'crm.lead'

    scan_session_id = fields.Many2one(
        comodel_name='event.lead.scan.session',
        string='Scan Session',
        ondelete='set null',
        index=True,
        help='The scanning session that captured this lead.',
    )
    event_registration_id = fields.Many2one(
        comodel_name='event.registration',
        string='Event Registration',
        ondelete='set null',
        index=True,
        help='The attendee this lead was captured from.',
    )
    scan_note = fields.Text(
        string='Scan Note',
        help='Note taken by the exhibitor at the moment of the scan.',
    )
    scan_score = fields.Selection(
        selection=[
            ('hot', 'Hot'),
            ('warm', 'Warm'),
            ('cold', 'Cold'),
        ],
        string='Scan Score',
    )
    scan_time = fields.Datetime(
        string='Scanned At',
        readonly=True,
        copy=False,
    )
    scanned_by_id = fields.Many2one(
        comodel_name='res.users',
        string='Scanned By',
        readonly=True,
        copy=False,
    )
    client_scan_uuid = fields.Char(
        string='Client Scan Reference',
        copy=False,
        index=True,
        readonly=True,
        help='Identifier generated by the scanner. Makes the scan '
             'submission idempotent, so a retried or queued scan never '
             'creates a duplicate lead.',
    )

    _sql_constraints = [
        # Design decision D4: a queued scan that is submitted twice must not
        # produce a second lead.
        ('client_scan_uuid_uniq', 'unique(client_scan_uuid)',
         'This scan has already been recorded.'),
        # Design decision D5: one lead per session and attendee.
        ('scan_session_registration_uniq',
         'unique(scan_session_id, event_registration_id)',
         'This attendee has already been captured in this session.'),
    ]

    @api.depends('scan_session_id')
    def _compute_scan_origin(self):
        """Kept for views that need a compact origin label."""
        for lead in self:
            if lead.scan_session_id:
                lead.scan_origin = lead.scan_session_id.name
            else:
                lead.scan_origin = False

    scan_origin = fields.Char(
        string='Scan Origin',
        compute='_compute_scan_origin',
    )

    def _is_scanned(self):
        self.ensure_one()
        return bool(self.scan_session_id)
